config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('explorea.events.urls', namespace='events')),
    path('accounts/', include('explorea.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

explorea/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    #path('logout/', auth_views.LogoutView.as_view(template_name="accounts/logged_out.html"), name='logout')
    path('logout/', auth_views.LogoutView.as_view(next_page="/events/"), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),

    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name = 'accounts/reset_password.html',
        email_template_name='accounts/reset_password_email.html'
        ),
        name='reset_password'),

    path('reset_password/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),

    path('reset-password/complete/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
]

explorea/events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('', views.index, name='index'),
    path('events/', views.event_listing, name='events'),
    path('eventrun/', views.eventrun_listing, name='eventrun'),
    #path('event/<str:name>', views.event_detail, name='detail'),
    path('events/detail/<int:pkey>', views.event_detail, name='detail_event'),
    path('events/update/<int:pkey>', views.update_event, name='update_event'),
    path('events/delete/<int:pkey>', views.delete_event, name='delete_event'),
    path('eventrun/detail/<int:pkey>', views.eventrun_detail, name='detail_eventrun'),
    path('eventrun/update/<int:event_run_id>', views.update_event_run, name='update_event_run'),
    path('eventrun/delete/<int:event_run_id>', views.delete_event_run, name='delete_event_run'),
    path('events/new/', views.create_event, name='create_event'),
    path('events/mine/', views.my_event, name='my_event'),
    path('events/mine/detail/<int:pkey>', views.my_event_detail, name='detail_my_event'),
    path('events/<int:event_id>/newrun/', views.create_event_run, name='create_event_run'),
]

explorea/accounts/models.py
from django.db import models

# Create your models here.

explorea/events/models.py
from django.db import models
from django.conf import settings


class Event(models.Model):

    FUN = 'FN'
    RELAX = 'RX'
    EXP = 'EX'
    SIGHTS = 'SI'

    CATEGORY_CHOICES= (
        (FUN, 'fun'),
        (RELAX, 'relax'),
        (EXP, 'experience'),
        (SIGHTS, 'sights')
    )

    host = models.ForeignKey(settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    location = models.CharField(max_length=500)

    category = models.CharField(
        max_length=20,
        choices = CATEGORY_CHOICES,
        default = FUN,
    )

    def __str__(self):
        return self.name

'''
class Event(models.Model):

    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    location = models.CharField(max_length=500)

    category = models.CharField(max_length=20)

    #host = models.ForeignKey(Event, on_delete=models.CASCADE)
    host = models.ForeignKey(settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE)

    def __str__(self):
        return self.name
'''

class EventRun(models.Model):

    event = models.ForeignKey(Event,
        on_delete=models.CASCADE)
    date = models.DateField(blank=False, null=False)
    time = models.TimeField(blank=False, null=False)
    seats_available = models.PositiveIntegerField(blank=False, null=False)
    price = models.DecimalField(max_digits=10,
        decimal_places=2, blank=False, null=False)

explorea/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from core.validators import validate_human_name

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])

    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        ]

#class EditProfileForm(UserChangeForm):
class EditProfileForm(forms.ModelForm):

    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password',
        ]



"""
class RegisterForm(forms.ModelForm):

    #username = forms.CharField(max_length=30, help_text='How will we call you?')
    #email = forms.EmailField()
    #first_name = forms.CharField(max_length=100)
    #last_name = forms.CharField(max_length=100)
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput,
        strip=False,
        help_text="Enter the same password as before, for verification.",
    )

    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
        ]
"""

explorea/events/forms.py
from django import forms

from .models import Event, EventRun


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        exclude = ['host']

class EventRunForm(forms.ModelForm):
    date = forms.DateField(input_formats=["%d.%m.%Y"],
        widget=forms.DateInput(format = '%d.%m.%Y'))

    class Meta:
        model = EventRun
        exclude = ['event']

explorea/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, get_user_model, update_session_auth_hash, login
from django.contrib.auth.forms import PasswordChangeForm

from .forms import RegisterForm, EditProfileForm

def change_password(request):

    if not request.user.is_authenticated:
        return redirect('login')

    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('/accounts/profile/')
        else:
            return render(request, 'accounts/change_password.html', {'form': form})

    form = PasswordChangeForm(user=request.user)
    return render(request, 'accounts/change_password.html', {'form': form})

def edit_profile(request):

    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            user = form.save()
            return redirect('profile')

    form = EditProfileForm(instance=request.user)
    return render(request, 'accounts/edit_profile.html', {'form': form} )

def profile(request):

    #return render(request, 'accounts/profile.html', {'user': request.user})
    return render(request, 'accounts/profile.html')


def register(request):

    if request.method == 'POST':

        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save()

            raw_password = form.cleaned_data.get('password1')

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            return redirect('profile')
        else:
            return render(request, 'accounts/register.html', {'form': form} )

    form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form} )

"""
def register(request):

    if request.method == 'POST':

        # create the form and populate it with data from the POST request
        form = RegisterForm(request.POST)

        # validate the data in the form
        if form.is_valid():

            # get the validated data from the form
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            password = form.cleaned_data.get('password1')

            # create and save the user
            User = get_user_model()
            u = User(username=username,
                     email=email,
                     first_name=first_name,
                     last_name=last_name)
            u.set_password(password)
            u.save()

            user = authenticate(username=username, password=password)
            login(request, user)

            # redirect to another page
            return redirect('profile')

    # if the request is of type GET
    form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form} )
"""

explorea/events/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Event, EventRun
from .forms import EventForm, EventRunForm


def index(request):
    return render(request, 'events/index.html')


def event_listing(request):

    events = Event.objects.all()

    return render(request, 'events/event_listing.html', {'events': events})

def eventrun_listing(request):

    events = EventRun.objects.all()

    return render(request, 'events/eventrun_listing.html', {'events': events})

def event_detail(request, pkey):

    event = Event.objects.get(pk=pkey)
    runs = event.eventrun_set.all().order_by('date', 'time')
    args = {'event': event, 'runs': runs}

    return render(request, 'events/event_detail.html', args)

def my_event_detail(request, pkey):

        event = Event.objects.get(pk=pkey)
        runs = event.eventrun_set.all().order_by('date', 'time')
        args = {'event': event, 'runs': runs}

        return render(request, 'events/my_event_detail.html', args)

def eventrun_detail(request, pkey):

    eventrun = EventRun.objects.get(pk=pkey)

    return render(request, 'events/eventrun_detail.html', {'run': eventrun})

@login_required
def create_event(request):

    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.host = request.user
            event.save()

            return redirect('my_event')

    form = EventForm()
    return render(request, 'events/create_event.html', {'form': form})

@login_required
def my_event(request):

    events = Event.objects.filter(host_id=request.user.id)

    return render(request, 'events/my_event.html', {'events': events})

def create_event_run(request, event_id):

    if request.method == 'POST':
        form = EventRunForm(request.POST)

        if form.is_valid():
            event_run = form.save(commit=False)
            event_run.event = Event.objects.get(pk=event_id)
            event_run.save()

            url = '/events/mine/detail/{}'.format(event_id)
            return redirect(url)

    args = {'form': EventRunForm()}
    return render(request, 'events/create_event_run.html', args)

def delete_event(request, pkey):

    Event.objects.get(pk=pkey).delete()
    return redirect('my_event')

def delete_event_run(request, event_run_id):

    run = EventRun.objects.get(pk=event_run_id)
    event_id = run.event.id
    run.delete()

    url = '/events/mine/detail/{}'.format(event_id)
    return redirect(url)

def update_event(request, pkey):
    event = Event.objects.get(pk=pkey)

    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)

        if form.is_valid():
            event = form.save()
            return redirect('my_event')

    form = EventForm(instance=event)
    return render(request, 'events/create_event.html', {'form': form})

def update_event_run(request, event_run_id):

    event_run = EventRun.objects.get(pk=event_run_id)

    if request.method == 'POST':
        form = EventRunForm(request.POST, instance=event_run)

        if form.is_valid():
            event_run = form.save()
            event_id = event_run.event.id
            url = '/eventrun/detail/{}'.format(event_run_id)
            return redirect(url)

    args = {'form': EventRunForm(instance=event_run)}
    return render(request, 'events/update_eventrun.html', args)

"""
def event_detail(request, name):
    data = {'Chill' : '<h2>Chill on the beach just for $400</h2>',
            'Camping': '<h2>Camp with us for $50</h2>',
            'Flying': '<h2>Fly for free</h2>'}

    selection = data.get(name)

    if selection:
        return HttpResponse(selection)
    else:
        return HttpResponse('No such event in offering for now')
"""

explorea/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'>

    {% csrf_token %}

    {% for field in form.visible_fields %}

        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}}{{ field }}</p>

    {% endfor %}

    {% if form.non_field_errors %}
        <ul>
        {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}

  <!--  {{ form.errors }}

    {{ form.as_p }} -->
    <input type="submit" value="Change">

</form>

{% endblock content %}

explorea/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block title %}
<title>Profile</title>
{% endblock title %}

{% block content %}
<div>

  <h2>Edit your profile</h2>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>

</div>
{% endblock content %}

explorea/templates/accounts/logged_out.html
{% extends 'base.html' %}

{% block content %}
<h2>Ciao</h2>

<p>You have been logged out. But if you decide to log in again, we will be happy to see you here.</p>

{% endblock content %}

explorea/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
<title>Login</title>
{% endblock title %}

{% block content %}


<div class="grid_container">
    <div class="login-image">

    </div>

    <div class="login_form">


        <form method="post">
            <h2>Login</h2>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <p>{{ field.label_tag }}{{ field }}</p>
            {% endfor %}

            <div>
                <button type="submit">Log in</button>
                <a class="forgot-pass" href="{% url 'accounts:reset_password' %}">Forgot password</a>
            </div>

        </form>

    </div>
</div>




{% endblock %}


<!--

<div class="grid_container">
    <div class="login-image">

    </div>
    <div class="login_form">


        <form method="post">
            <h2>Login</h2>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <p>{{ field.label_tag }}{{ field }}</p>
            {% endfor %}

            <div>
                <button type="submit">Log in</button>
                <a class="forgot-pass" href="{% url 'accounts:reset_password' %}">Forgot password</a>
            </div>

        </form>

    </div>

</div>
 -->

explorea/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<br>
<table>
    <tr>
        <td>Username: </td><td>{{ user.username }}</td>
    </tr>
    <tr>
        <td>First Name: </td><td>{{ user.first_name }}</td>
    </tr>
    <tr>
        <td>Last Name: </td><td>{{ user.last_name }}</td>
    </tr>
    <tr>
        <td>Email: </td><td>{{ user.email }}</td>
    </tr>
     <tr>
        <td>Joined: </td><td>{{ user.date_joined }}</td>
    </tr>
</table>


<br><br>

{% if user.is_authenticated %}
<a href="/accounts/profile/edit/">Edit</a>
<a href="/accounts/change_password/">Change Password</a>
{% endif %}

{% endblock content %}

explorea/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}
<title>Register</title>
{% endblock title %}

{% block content %}
<div class="grid_container">
    <div class="login-image">

    </div>
    <div class="register_form">


        <form method="post">
            <h2>Register</h2>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <p>{{ field.label_tag }}{{ field }}</p>
            {% endfor %}

            <button type="submit">Sign up</button>
        </form>

    </div>

</div>
{% endblock content %}

explorea/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block title %}
<title>Password Reset</title>
{% endblock title %}

{% block content %}
<div>

  <h2>Password Reset</h2>
  <p>Enter your email below and click "Submit". We will send you the reset link to your email immediately.</p>

  <form method="post">
    {% csrf_token %}

    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}} {{ field }}</p>

    {% endfor %}

    <button type="submit">Save</button>
  </form>

</div>
{% endblock content %}

explorea/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site! XXXXXXX" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}